### ISSUE TITLE
No module named 'pydantic'

### ISSUE THREAD

**Issue by depech25** [omirete/telepybot#1]
A problem with:
https://github.com/omirete/telepybot/blob/master/examples/send_message.py
![изображение](https://user-images.githubusercontent.com/105047275/196525206-c7635d32-66fe-4455-a332-22283bfd031e.png)
I just cant install any telegrambot class... Can you please help with?

**Comment by depech25** [comment]
Sorry, i had no installed  "pydantic" class. So i install it and all works well!

**Comment by omirete** [comment]
Hi @Depech101, thank you for posting this issue!

I discovered that Pydantic was not specified as a dependency in the `pyproject.toml` file. Because of this, it was not being automatically installed when installing the telepybot library.

I have fixed it now with [this commit](https://github.com/omirete/telepybot/commit/98ad11eb66c28dc79dfbf62bd3fd24a50d0be4d2).

Thanks again!
